//
//  ShowOrderModels.swift
//  CleanStore
//
//  Created by Bradley.yoon on 2023/06/09.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ShowOrder
{
    // MARK: Use cases

    enum GetOrder {
        struct Request {
            
        }
        struct Response {
            var order: Order
        }
        struct ViewModel {
            struct DisplayedOrder {
                var id: String
                var date: String
                var email: String
                var name: String
                var total: String
            }
            var displayedOrder: DisplayedOrder
        }
    }


    enum Something
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
}
