//
//  ShowOrderRouter.swift
//  CleanStore
//
//  Created by Bradley.yoon on 2023/06/09.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShowOrderRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
    func routeToEditOrder(segue: UIStoryboardSegue?)
}

protocol ShowOrderDataPassing
{
  var dataStore: ShowOrderDataStore? { get }
}

class ShowOrderRouter: NSObject, ShowOrderRoutingLogic, ShowOrderDataPassing
{
  weak var viewController: ShowOrderViewController?
  var dataStore: ShowOrderDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}
    
    func routeToEditOrder(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! CreateOrderViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToEditOrder(source: dataStore!, destination: &destinationDS)
        }else {
            let destinationVC = segue?.destination as! CreateOrderViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToEditOrder(source: dataStore!, destination: &destinationDS)
        }
    }

  // MARK: Navigation
    func navigationToEditOrder(segue: ShowOrderViewController, destination: CreateOrderViewController) {
        
    }
  
  // MARK: Passing data
    func passDataToEditOrder(source: ShowOrderDataStore, destination: inout CreateOrderDataStore) {
        print(source.order)
        destination.orderToEdit = source.order
    }
}
