//
//  ListOrdersWorker.swift
//  CleanStore
//
//  Created by Bradley.yoon on 2023/06/07.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListOrdersWorker
{
  func doSomeWork()
  {
  }
}
