//
//  CreateOrderModels.swift
//  CleanStore
//
//  Created by Bradley.yoon on 2023/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateOrder
{
    // MARK: Use cases
    

    enum FormatExpirationDate {
        struct Request {
            var date: Date

        }
        struct Response {
            var date: Date
        }
        struct ViewModel {
            var date: String
        }
    }

    struct OrderFormFields {
        var firstName: String
        var lastName: String
        var phone: String
        var email: String

        var billingAddressStreet1: String
        var billingAddressStreet2: String
        var billingAddressCity: String
        var billingAddressState: String
        var billingAddressZIP: String
        var paymentMethodCreditCardNumber: String
        var paymentMethodCVV: String
        var paymentMethodExpirationDate: Date
        var paymentMethodExpirationDateString: String
        // MARK: Shipping info
        var shipmentAddressStreet1: String
        var shipmentAddressStreet2: String
        var shipmentAddressCity: String
        var shipmentAddressState: String
        var shipmentAddressZIP: String
        var shipmentMethodSpeed: Int
        var shipmentMethodSpeedString: String
        // MARK: Misc
        var id: String?
        var date: Date
        var total: NSDecimalNumber
    }
    
    enum CreateOrder {
        struct Request {
            var orderFormFields: OrderFormFields
        }
        struct Response {
            var order: Order?
        }
        struct ViewModel {
            var order: Order?
        }
    }
    
    enum EditOrder {
        struct Request {
            
        }
        struct Response {
            var order: Order
        }
        struct ViewModel {
            var orderFormFields: OrderFormFields
        }
    }
    
    enum UpdateOrder {
        struct Request {
            var orderFormFields: OrderFormFields
        }
        struct Response {
            var order: Order?
        }
        struct ViewModel {
            var order: Order?
        }
    }
}
